### ISSUE TITLE
ELRS Support?

### ISSUE THREAD

**Issue by neo7530** [g3gg0/DigiJoystick_FPV#1]
Hi, 

ich habe den Adapter aufgebaut, in der Hoffnung mein Express-LRS Empfänger würde laufen, da er am Ausgang auch Crossfire spricht. Ich habe also meinen Digispark programmiert, zwischen PB2 und PB3 eine Brücke eingelötet, und den TXD vom ELR-Empfänger an PB0 gelötet. USB-Joystick wird erkannt, allerdings kommen die Stick-Werte nicht an. Hab parallel dazu per LA gelauscht, Seriell liegt an 0xC8, 0x16 ...... usw. Hab ich was übersehen?

Gruß, Marco.

**Comment by neo7530** [comment]
Ahhh, es läuft... Lag am usb3 Port, der mochte nicht.

Gute Arbeit 👍

**Comment by g3gg0** [comment]
sehr schön, freut mich dass es klappt :)
gibts fotos und erfahrungsberichte?

**Comment by neo7530** [comment]
![IMG_20210512_184838.jpg](https://user-images.githubusercontent.com/6802079/118034138-ec294e00-b369-11eb-8970-3885b4718d83.jpg)

Läuft, allerdings nur an echten usb2 ports, an usb3 fliegt er kurz nach dem erkennen wieder raus.

**Comment by g3gg0** [comment]
Danke dir.

Ja ist bei vielen "geht gerade so..."-USB1-Lösungen der Fall.
An was das genau liegt und ob es V-USB Implementierungen gibt, bei denen das nicht passiert, das weiss ich leider nicht.

Bei mir klappts an einem USB3 port, allerdings hab ich hin und wieder mal einen disconnect.
Aber doch recht selten.

**Comment by neo7530** [comment]
Bin vorhin 2 Stunden sim geflogen, und hatte kurz vor Schluss nen disconnect. Aber ansonsten läuft es super 😊

**Comment by g3gg0** [comment]
There was an update - maybe those sporadic reset issues are gone now also
